version: '3.8'

services:

  agenda-app-db-svc:
    image: postgres:18
    container_name: agenda-app-db
    environment:
      POSTGRES_DB: agenda-app-db
      POSTGRES_USER: admin-dev
      POSTGRES_PASSWORD: pwd-dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - red-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin-dev -d agenda-app-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  agenda-app-svc:
    build: 
      context: ../
      dockerfile: artifacts/server/Dockerfile.dev
    container_name: agenda-app-api
    restart: always
    environment:
      - IN_DOCKER=true
    ports:
      - "8080:8080"
    depends_on:
      agenda-app-db-svc:
        condition: service_healthy
    networks:
      - red-app
    volumes:
      - ../:/agenda-app
      - /agenda-app/bin 

volumes:
  db_data:

networks:
  red-app:
    driver: bridge
